import { Flex, Text, Container, Divider, Img } from "@chakra-ui/react";
import SanityBlockContent from "@sanity/block-content-to-react";
import Head from "next/head";
import { useRouter } from "next/router";

import { client, urlFor } from "../../client/client";
import Footer from "../components/Footer";
import Navbar from "../components/navbar";
import Rightbar from "../components/Rightbar";

export default function Home({ results, feature }) {
	const router = useRouter();
	// console.log({ results });
	return (
		<Flex direction="column">
			<Head>
				<title>Sanity Blog</title>
				<meta name="description" content="Generated by Khoa" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Container maxW="1440px" mb="100px">
				<Flex w={{ base: "800px", xl: "1200px", "2xl": "1440px" }} gap="2">
					<Flex direction="column" mt="150px" w={{ base: "100%", lg: "65%" }}>
						{results?.map((post, _i) => (
							<>
								<Divider />
								<Flex key={_i} w="100%" h="200px" py="1" px="2" gap="2" mx="100px" my="2" overflow="hidden">
									<Flex direction="column" gap="2" w="60%">
										<Text
											fontWeight="bold"
											fontSize={["10pt", "11pt", "13pt", "15pt"]}
											onClick={() => router.push(`/post/${post.slug.current}`)}
											cursor="pointer"
										>
											{post.title}
										</Text>
										<Flex fontSize={["8pt", "12pt", "13pt", "14pt"]}>
											<SanityBlockContent blocks={post.begin} />
										</Flex>
									</Flex>
									<Flex w="40%" onClick={() => router.push(`/post/${post.slug.current}`)} cursor="pointer">
										<Img w="70%" h="180px" src={urlFor(post.mainImage)} objectFit="cover" />
									</Flex>
								</Flex>
								<Divider />
							</>
						))}
					</Flex>
					<Flex w="25%" display={{ base: "none", lg: "flex" }}>
						<Rightbar feature={feature} />
					</Flex>
				</Flex>
			</Container>
			<Footer />
		</Flex>
	);
}

export const getServerSideProps = async () => {
	const query = '*[ _type == "post" ] | order(_createdAt desc)';
	const feaQuery = '*[ _type == "post" && isfeature == true]';

	const results = await client.fetch(query);
	// console.log({ results });

	const feature = await client.fetch(feaQuery);
	// console.log({ feature });
	return {
		props: {
			results,
			feature,
		},
	};
};
