import { Container, Divider, Flex, Heading, Img, Text } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";
import { BsCalendar3 } from "react-icons/bs";
import SanityBlockContent from "@sanity/block-content-to-react";

import { client, urlFor } from "../../../client/client";
import Navbar from "../../components/navbar";
import Footer from "../../components/Footer";

const PostDetail = ({ body, title, image, createdAt, author }) => {
	// console.log(body, title, image);
	return (
		<Flex direction="column">
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by Khoa" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Container maxW="1200px" mb="100px">
				<Flex w={{ base: "1000px", xl: "1200px", "2xl": "1440px" }} direction="column" mt="150px" mx="3">
					<Text fontSize={{ base: "30pt", xl: "14pt" }} fontWeight="bold">
						{title}
					</Text>
					<Flex align="center" gap="1" mt="2" color="gray.500">
						<BsCalendar3 />
						<Text>{createdAt.split("T")[0]}</Text>
					</Flex>
					<Divider p="5" />
					<Img src={image && urlFor(image)} my="5" objectFit="cover" w="full" h="600px" rounded="10px" />
					<Flex fontSize={{ base: "30pt", xl: "14pt" }} fontWeight="500">
						<SanityBlockContent blocks={body} />
					</Flex>
				</Flex>
			</Container>
			<Footer />
		</Flex>
	);
};

export default PostDetail;

export const getServerSideProps = async ({ params: { slug } }) => {
	const query = `*[ _type == "post" && slug.current == '${slug}' ][0]`;

	const result = await client.fetch(query);
	console.log(result);
	return {
		props: {
			body: result.body,
			title: result.title,
			image: result.mainImage,
			createdAt: result._createdAt,
		},
	};
};
